HCM-MOZ-IMPEL/health-campaign-field-worker-app-impel

apps/health_campaign_field_worker_app/lib/widgets/beneficiary/resource_beneficiary_card.dart, apps/health_campaign_field_worker_app/lib/widgets/member_card/member_card.dart, packages/digit_components/lib/widgets/atoms/digit_reactive_dropdown.dart
1)made dropdown disabled in detalhes dos recursos - hcm - 862 
2)'Record Delivery' button enabled at all times - hcm 867
=> HMC- 862,867

apps/health_campaign_field_worker_app/lib/pages/beneficiary/deliver_intervention.dart, apps/health_campaign_field_worker_app/lib/pages/inventory/stock_reconciliation/stock_reconciliation.dart, apps/health_campaign_field_worker_app/lib/utils/i18_key_constants.dart, apps/health_campaign_field_worker_app/lib/widgets/beneficiary/resource_beneficiary_card.dart, apps/health_campaign_field_worker_app/lib/widgets/member_card/member_card.dart
1)Replace the label "ineligible" for "householder head" - hcm-611
2)Add a field to capture if there were a wasted SPAQ - hcm -865
3)Update the labels in inventory flow to match the NCMP materials and forms - hcm-868
=> SMC feature HCM- 611,865,868

apps/health_campaign_field_worker_app/lib/pages/checklist/checklist.dart, apps/health_campaign_field_worker_app/lib/utils/i18_key_constants.dart
=> Change Create checklist to fill checklist label

apps/health_campaign_field_worker_app/lib/pages/boundary_selection.dart
=> Automatically select highest boundary value

apps/health_campaign_field_worker_app/lib/pages/beneficiary/beneficiary_details.dart, apps/health_campaign_field_worker_app/lib/pages/beneficiary/household_overview.dart, apps/health_campaign_field_worker_app/lib/pages/beneficiary_registration/individual_details.dart, apps/health_campaign_field_worker_app/lib/widgets/beneficiary/view_beneficiary_card.dart, apps/health_campaign_field_worker_app/lib/widgets/member_card/member_card.dart
=> Remove DOB and Age in beneficiary

apps/health_campaign_field_worker_app/lib/data/repositories/local/task.dart, apps/health_campaign_field_worker_app/lib/pages/home.dart, apps/health_campaign_field_worker_app/lib/widgets/progress_bar/beneficiary_progress.dart
1)track progress through individual counts
=> progress tracking  HCM-588

apps/health_campaign_field_worker_app/lib/pages/beneficiary/deliver_intervention.dart, apps/health_campaign_field_worker_app/lib/pages/beneficiary_registration/individual_details.dart, apps/health_campaign_field_worker_app/lib/pages/complaints/registration/complaints_details.dart, apps/health_campaign_field_worker_app/lib/utils/utils.dart
=> Mobile limit to 10 and make delivery comment Text

apps/health_campaign_field_worker_app/lib/pages/beneficiary/household_overview.dart, apps/health_campaign_field_worker_app/lib/pages/search_beneficiary.dart, apps/health_campaign_field_worker_app/lib/utils/extensions/context_utility.dart, apps/health_campaign_field_worker_app/lib/utils/i18_key_constants.dart
Remove certain actions/components from the registrar's role and distributor
=> Remove action/components Hcm-598

apps/health_campaign_field_worker_app/lib/pages/beneficiary/household_overview.dart
Edit button enabled for household details
=> HCM-983,edit button enabled for household details

apps/health_campaign_field_worker_app/lib/pages/beneficiary_registration/individual_details.dart, apps/health_campaign_field_worker_app/lib/utils/i18_key_constants.dart
New codes added for individual - household head ,name ,surname
=> HCM-984,new code for individual - household head

apps/health_campaign_field_worker_app/lib/pages/beneficiary/side_effects.dart, apps/health_campaign_field_worker_app/lib/pages/inventory/record_stock/stock_details.dart, apps/health_campaign_field_worker_app/lib/pages/inventory/record_stock/warehouse_details.dart, apps/health_campaign_field_worker_app/lib/pages/inventory/stock_reconciliation/stock_reconciliation.dart, apps/health_campaign_field_worker_app/lib/widgets/member_card/member_card.dart, packages/digit_components/lib/widgets/digit_checkbox_tile.dart
View HH Details button added when ,BeneficiaryRefused or SideEffects recorded
=> HCM-987,HH Details-BeneficiaryRefused ,SideEffects screen

apps/health_campaign_field_worker_app/lib/blocs/search_households/search_households.dart, apps/health_campaign_field_worker_app/lib/pages/beneficiary/widgets/household_acknowledgement.dart, apps/health_campaign_field_worker_app/lib/pages/beneficiary_registration/beneficiary_acknowledgement.dart, apps/health_campaign_field_worker_app/lib/pages/beneficiary_registration/individual_details.dart, apps/health_campaign_field_worker_app/lib/router/app_router.dart, apps/health_campaign_field_worker_app/lib/router/app_router.gr.dart
view household button when head registered
=> Hcm 985, view household button when head registered

apps/health_campaign_field_worker_app/lib/widgets/progress_bar/beneficiary_progress.dart
Registration date check moved from projectBeneficiary to task
=> HCM-989 ,registration date check moved from projectBeneficiary to task 

apps/health_campaign_field_worker_app/lib/utils/i18_key_constants.dart, apps/health_campaign_field_worker_app/lib/widgets/member_card/member_card.dart
If the child went to HF(in first cycle),translation of the message changed
=> Hcm 988,if the child went to HF,translation of the message changed

apps/health_campaign_field_worker_app/lib/widgets/member_card/member_card.dart
removed isBeneficiaryReferred check so as to allow edit
=> HCM-986, removed isBeneficiaryReferred check so as to allow edit

apps/health_campaign_field_worker_app/lib/pages/beneficiary/refer_beneficiary.dart
In the refer flow, the APS added
=> HCM-996 ,APS added in refer beneficiary

apps/health_campaign_field_worker_app/lib/utils/i18_key_constants.dart, apps/health_campaign_field_worker_app/lib/widgets/member_card/member_card.dart
Reverts HCM-MOZ-IMPEL/health-campaign-field-worker-app-impel#26
=> Revert "Hcm 988,if the child went to HF,translation of the message changed"

apps/health_campaign_field_worker_app/lib/widgets/progress_bar/beneficiary_progress.dart
HCM-989, used clientAuditDetails.createdTime for check
=> HCM-989, dateTime check changed in tasks

apps/health_campaign_field_worker_app/lib/pages/beneficiary_registration/individual_details.dart
HH,register/Individual spaces are not syncing
=> HCM-1009,HH,register/Individual spaces are not syncing

apps/health_campaign_field_worker_app/lib/pages/beneficiary_registration/household_location.dart, apps/health_campaign_field_worker_app/lib/utils/i18_key_constants.dart, apps/health_campaign_field_worker_app/lib/widgets/progress_bar/beneficiary_progress.dart
=> Added landmark, accuracy and target to 250

apps/health_campaign_field_worker_app/lib/pages/beneficiary_registration/individual_details.dart, apps/health_campaign_field_worker_app/lib/utils/utils.dart
min3 validation text fix in utils
=> min3 validation text fix

apps/health_campaign_field_worker_app/lib/pages/boundary_selection.dart
=> highest boundary field as mandatory

apps/health_campaign_field_worker_app/lib/pages/inventory/record_stock/stock_details.dart
=> validation on the quantity of stock issued field

apps/health_campaign_field_worker_app/lib/pages/attendance/track-attendance_inbox.dart, apps/health_campaign_field_worker_app/lib/pages/attendance/track_attendance_mark.dart, apps/health_campaign_field_worker_app/lib/pages/attendance/track_attendance_session_selection.dart, apps/health_campaign_field_worker_app/lib/utils/i18_key_constants.dart
1. localization added
2. submit button restriction for if the selected date is exceeding the event date , we are showing the snack message
=> restriction applied on the date exceed the event end date

apps/health_campaign_field_worker_app/lib/data/repositories/local/boundary.dart
=> hcm-boundary type check added

apps/health_campaign_field_worker_app/lib/blocs/search_households/project_beneficiaries_downsync.dart, apps/health_campaign_field_worker_app/lib/blocs/search_households/search_households.dart, apps/health_campaign_field_worker_app/lib/blocs/search_households/search_households.freezed.dart, apps/health_campaign_field_worker_app/lib/data/repositories/local/individual.dart, apps/health_campaign_field_worker_app/lib/data/repositories/local/project_beneficiary.dart, apps/health_campaign_field_worker_app/lib/data/repositories/local/task.dart, apps/health_campaign_field_worker_app/lib/models/entities/individual.dart, apps/health_campaign_field_worker_app/lib/models/entities/name.dart, apps/health_campaign_field_worker_app/lib/models/entities/project_beneficiary.dart, apps/health_campaign_field_worker_app/lib/models/entities/task.dart, apps/health_campaign_field_worker_app/lib/pages/search_beneficiary.dart, apps/health_campaign_field_worker_app/lib/widgets/progress_bar/beneficiary_progress.dart, apps/health_campaign_field_worker_app/pubspec.yaml
This is a performance hot fix for search by text
=> added pagination for search by head

apps/health_campaign_field_worker_app/lib/pages/health_field_worker/create_referral/record_facility_details.dart, apps/health_campaign_field_worker_app/lib/pages/health_field_worker/create_referral/record_referral_details.dart
hcm-1584 , hf_referral changes , removed age,gender,beneficiary fields , and date field non editable
=> hcm-1584 , hf_referral changes , removed age,gender,beneficiary fields

apps/health_campaign_field_worker_app/lib/pages/search_referrals.dart
HCM-1584 , height changed for create new referral button
=> HCM-1584 , height changed for create new referral button

apps/health_campaign_field_worker_app/lib/widgets/sidebar/side_bar.dart, apps/health_campaign_field_worker_app/pubspec.yaml
=> Style changes upon UI/ux
